
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"><?php echo _('Producto')?></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
					   	<?php echo _('Registrar Producto')?> 
                    </div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<!--  <form action="<?php echo BASE_URL?>usuario/insertar" method="POST" class="form-signin"> -->
								<form action="<?php echo BASE_URL?>producto/insertar" method="POST"
									class="form-signin" id="productoEditar">
<!-- 									<div class="col-md-6"> -->
										<div class="form-group">
											<label><?php echo _('Code')?></label> 
											<input type="text" class="form-control" name="productCode" id="productCode" autofocus />
										</div>
										<div class="form-group">
											<label><?php echo _('Name')?></label> 
											<input type="text" class="form-control" name="productName" id="productName" />
										</div>
										<div class="form-group">
											<label><?php echo _('Line')?></label> 
											<input type="text" class="form-control" name="productLine" id="productLine" />
										</div>
										<div class="form-group">
											<label><?php echo _('Scale')?></label> 
											<input type="text" class="form-control" name="productScale" id="productScale" />
										</div>
										<div class="form-group">
											<label><?php echo _('Vendor')?></label> 
											<input type="text" class="form-control" name="productVendor" id="productVendor" />
										</div>
<!-- 									</div> -->
<!-- 									<div class="col-md-6"> -->
										<div class="form-group">
											<label><?php echo _('Description')?></label> 
											<textarea rows="4" cols="3" class="form-control" name="productDescription" id="productDescription" ></textarea>
										</div>
										<div class="form-group">
											<label><?php echo _('InStock')?></label> 
											<input type="text" class="form-control" name="quantityInStock" id="quantityInStock" />
										</div>
										<div class="form-group">
											<label><?php echo _('Price')?></label> 
											<input type="text" class="form-control" name="buyPrice" id="buyPrice" />
										</div>
										<div class="form-group">
											<label><?php echo _('MSRP')?></label> 
											<input type="text" class="form-control" name="MSRP" id="MSRP" />
										</div>																	
										
										<!-- 		<button class="btn text-muted text-center btn-success" type="submit">Guardar</button> -->
										<button class="btn text-muted text-center btn-success"
											type="button" id="btnRegistrar">Registrar</button>
<!-- 									</div> -->
								</form>
								<div id="zonaRespuesta"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>