<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h2><?php echo _('Registro de Producto')?></h2>
			</div>
		</div>

		<hr />
		
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="<?php echo BASE_URL?>producto/formInsertar">Nuevo</a>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<br/>
							<table class="table table-striped table-bordered table-hover" id="dataTables-producto">
								<thead>
									<tr>
										<th><?php echo _('Code')?></th>
										<th><?php echo _('Name')?></th>
										<th><?php echo _('Line')?></th>
										<th><?php echo _('Scale')?></th>
										<th><?php echo _('Vendor')?></th>
										<th><?php echo _('Description')?></th>
										<th><?php echo _('InStock')?></th>
										<th><?php echo _('Price')?></th>
										<th><?php echo _('MSRP')?></th>
										<th><?php echo _('Editar')?></th>
										<th><?php echo _('Eliminar')?></th>
									</tr>
								</thead>
								<tbody id="body_usuarios">
								<?php while( $registroProducts = $this-> dataProducts-> fetch_object()):?>
									<tr>
										<td><?php echo $registroProducts-> productCode?></td>
										<td><?php echo $registroProducts-> productName?></td>
										<td><?php echo $registroProducts-> productLine?></td>
										<td><?php echo $registroProducts-> productScale?></td>
										<td><?php echo $registroProducts-> productVendor?></td>
										<td><?php echo $registroProducts-> productDescription?></td>
										<td><?php echo $registroProducts-> quantityInStock?></td>
										<td><?php echo $registroProducts-> buyPrice?></td>
										<td><?php echo $registroProducts-> MSRP?></td>
										<td style="text-align: center" >
											<a style="color:#000" class="glyphicon glyphicon-pencil" href="<?php echo BASE_URL?>producto/formEditar/<?php echo $registroProducts -> productCode?>"></a>
										</td>
										<td style="text-align: center" >
											<a style="color:red" class="glyphicon glyphicon-remove" href="<?php echo BASE_URL?>producto/eliminar/<?php echo $registroProducts -> productCode?>"></a>
										</td>
									</tr>
								<?php endwhile;?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
