
<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"><?php echo _('Usuario')?></h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
					   	<?php echo _('Editar Usuario')?> 
                    </div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-6">
								<!--  <form action="<?php echo BASE_URL?>usuario/editar" method="POST" class="form-signin"> -->
								<form action="<?php echo BASE_URL?>usuario/editar" method="POST"
									class="form-signin" id="usuarioEditar">
									<div class="form-group">
										<label><?php echo _('Usuario')?></label> <input type="text"
											placeholder="<?php echo _('ID USUARIO')?>"
											class="form-control" name="idusuario" id="idusuario"
											value="<?php echo $this-> data-> idusuario?>" readonly />
									</div>
									<div class="form-group">
										<label><?php echo _('Nombre')?></label> <input type="text"
											placeholder="<?php echo _('NOMBRE')?>" class="form-control"
											name="nombre" id="nombre"
											value="<?php echo $this-> data-> nombre ?>" />
									</div>
									<div class="form-group">
										<label><?php echo _('Email')?></label> <input type="text"
											placeholder="<?php echo _('EMAIL')?>" class="form-control"
											name="email" name="email" id="email"
											value="<?php echo $this-> data-> email?>" />
									</div>
									<div class="form-group">
										<label><?php echo _('Rol')?></label> <select name="rol"
											class="form-control" id="rol">
											<option value="Administrador"
												<?php echo $this-> data-> rol == 'Administrador' ? 'selected': ''?>> <?php echo _('Administrador')?></option>
											<option value="Supervisor"
												<?php echo $this-> data-> rol == 'Supervisor' ? 'selected': ''?>> <?php echo _('Supervisor')?></option>
											<option value="Usuario"
												<?php echo $this-> data-> rol == 'Usuario' ? 'selected': ''?>> <?php echo _('Usuario')?></option>
										</select>
									</div>
									<!-- 		<button class="btn text-muted text-center btn-success" type="submit">Guardar</button> -->
									<button class="btn text-muted text-center btn-success"
										type="button" id="btnGuardar">Guardar Cambios</button>

								</form>
								<div id="zonaRespuesta"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>