<!--PAGE CONTENT -->
<div id="content">

	<div class="inner">
		<div class="row">
			<div class="col-lg-12">
				<h2><?php echo _('Registro de Usuario')?></h2>
			</div>
		</div>

		<hr />
		
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="<?php echo BASE_URL?>usuario/formInsertar">Nuevo</a>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<br/>
							<table class="table table-striped table-bordered table-hover" id="dataTables-usuarios">
								<thead>
									<tr>
										<th><?php echo _('idusuario')?></th>
										<th><?php echo _('nombre')?></th>
										<th><?php echo _('clave')?></th>
										<th><?php echo _('email')?></th>
										<th><?php echo _('rol')?></th>
										<th><?php echo _('fecha ingreso')?></th>
										<th></th>
									</tr>
								</thead>
								<tbody id="body_usuarios">
								<?php while( $registro = $this-> data-> fetch_object()):?>
									<tr>
										<td><?php echo $registro-> idusuario?></td>
										<td><?php echo $registro-> nombre?></td>
										<td><?php echo $registro-> clave?></td>
										<td><?php echo $registro-> email?></td>
										<td><?php echo $registro-> rol?></td>
										<td><?php echo $registro-> fechareg?></td>
										<td>
											<a href="<?php echo BASE_URL?>usuario/formEditar/<?php echo $registro -> idusuario?>">Editar</a> |
											<a href="<?php echo BASE_URL?>usuario/eliminar/<?php echo $registro -> idusuario?>">Eliminar</a>
										</td>
									</tr>
								<?php endwhile;?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
